parameters:
  - name: agentPool
    type: object
    default:
      name: 'managed-devops-pool-02'
  - name: pipelineTemplate
    type: object
    default:
      ref: 'main'
      vargroup: pd

resources:
  repositories:
    - repository: azure-build-pipeline
      type: git
      name: KCB-DevOps/azure-build-pipeline
      ref: ${{ parameters.pipelineTemplate.ref }}

trigger:
  branches:
    include:
      - 'develop'

variables:
  - group: 'kcb-global-pipeline-variables-${{ parameters.pipelineTemplate.vargroup }}'
  - name: projectName
    value: 'springboot-demoapp-jenkins'
  - name: serviceName
    value: 'springboot-demoapp-jenkins'
  - name: scrumTeam
    value: '(_scrum-team)'
  - name: version
    value: 'v1'
  - name: jdkVersion
    value: 21

stages:
  - template: /integretion/maven-springboot/main.yml@azure-build-pipeline
    parameters:
      projectName: ${{ variables.projectName }}
      serviceName: ${{ variables.serviceName }}
      agentPool: ${{ parameters.agentPool }}
      pipelineTemplate: ${{ parameters.pipelineTemplate }}
